title: Zhengji Li's personal blog
description: "what the heck is going on"
owner_name: Zhengji Li
github_username: xinjiav2
github_repo: "CSSE1-2-Blog" 
baseurl: "/CSSE1-2-Blog"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
minima:
  nav_pages:
    - navigation/blog.md
    - navigation/search.md
